### ISSUE TITLE
个别类型的消息需要对齐接口文档

### ISSUE THREAD

**Issue by helsonxiao** [NICEXAI/WeWorkFinanceSDK#15]
感谢开源本项目，下面是我发现的一些问题。

## 音频存档消息

https://developer.work.weixin.qq.com/document/path/91774#%E9%9F%B3%E9%A2%91%E5%AD%98%E6%A1%A3%E6%B6%88%E6%81%AF

没有完全对齐接口文档

https://github.com/NICEXAI/WeWorkFinanceSDK/blob/883b3e0c3b7b6d9730d580078be188895eaec1c7/message.go#L315-L327

## 互通红包消息

祝福语数据类型错误

https://github.com/NICEXAI/WeWorkFinanceSDK/blob/883b3e0c3b7b6d9730d580078be188895eaec1c7/message.go#L366

## 视频号消息

视频号消息描述的数据类型以及注释错误

https://github.com/NICEXAI/WeWorkFinanceSDK/blob/883b3e0c3b7b6d9730d580078be188895eaec1c7/message.go#L379

## 微盘文件消息

微盘文件消息有待支持

**Comment by NICEXAI** [comment]
代码已合并，非常感谢你的PR

**Comment by helsonxiao** [comment]
## 遗漏 tag

`SphFeed` 和 `Voiptext` 缺少 tag

https://github.com/NICEXAI/WeWorkFinanceSDK/blob/2b560f24db9ff804a516f2d2c5c7c4ba3082ac28/message.go#L374-L391
